"""
Названия стран → двухбуквенные коды ISO 3166 («Germany» → «DE»).

Нужны для территории в отчётах площадок: Believe пишет страну английским
названием («Russian federation», «Korea, republic of»), а в Dista и в отчёте
правообладателю территория стоит кодом («DE», «NO», «MX»). Сверено с
детализированным отчётом правообладателю из Dista (24.09.2026).

СЛОВАРЬ СОБРАН ПО НАСТОЯЩИМ ОТЧЁТАМ Believe за май 2026 (225 названий, все
три файла: RU, KZ, AE) и лежит в коде готовым, без библиотеки: написание у
площадки своё («Bosnia and herzegovi» обрезано, «China mainland»,
«Sudan (the)»), и общая библиотека стран его бы всё равно не узнала.

Незнакомое название НЕ ПОДМЕНЯЕТСЯ и не выбрасывается — остаётся как есть:
новую страну лучше увидеть словом, чем потерять. Особые значения площадки
тоже кодами: «Worldwide» → WW, «Serbia and montenegro» → CS (так их пишет и
Dista).
"""

COUNTRY_CODES = {
    'afghanistan': 'AF',
    'albania': 'AL',
    'algeria': 'DZ',
    'american samoa': 'AS',
    'andorra': 'AD',
    'angola': 'AO',
    'anguilla': 'AI',
    'antigua and barbuda': 'AG',
    'argentina': 'AR',
    'armenia': 'AM',
    'aruba': 'AW',
    'australia': 'AU',
    'austria': 'AT',
    'azerbaijan': 'AZ',
    'bahamas': 'BS',
    'bahrain': 'BH',
    'bangladesh': 'BD',
    'barbados': 'BB',
    'belarus': 'BY',
    'belgium': 'BE',
    'belize': 'BZ',
    'benin': 'BJ',
    'bermuda': 'BM',
    'bhutan': 'BT',
    'bolivia': 'BO',
    'bosnia and herzegovi': 'BA',
    'botswana': 'BW',
    'brazil': 'BR',
    'brunei darussalam': 'BN',
    'bulgaria': 'BG',
    'burkina faso': 'BF',
    'burundi': 'BI',
    'cambodia': 'KH',
    'cameroon': 'CM',
    'canada': 'CA',
    'cape verde': 'CV',
    'cayman islands': 'KY',
    'central african republic': 'CF',
    'chad': 'TD',
    'chile': 'CL',
    'china mainland': 'CN',
    'colombia': 'CO',
    'comoros': 'KM',
    'congo': 'CG',
    'congo, the democratic republic of the': 'CD',
    'cook islands': 'CK',
    'costa rica': 'CR',
    'croatia': 'HR',
    'cyprus': 'CY',
    'czech republic': 'CZ',
    'côte d ivoire': 'CI',
    'denmark': 'DK',
    'djibouti': 'DJ',
    'dominica': 'DM',
    'dominican republic': 'DO',
    'ecuador': 'EC',
    'egypt': 'EG',
    'el salvador': 'SV',
    'equatorial guinea': 'GQ',
    'eritrea': 'ER',
    'estonia': 'EE',
    'eswatini': 'SZ',
    'ethiopia': 'ET',
    'falkland islands (malvinas)': 'FK',
    'faroe islands': 'FO',
    'fiji': 'FJ',
    'finland': 'FI',
    'france': 'FR',
    'french guiana': 'GF',
    'french polynesia': 'PF',
    'gabon': 'GA',
    'gambia': 'GM',
    'georgia': 'GE',
    'germany': 'DE',
    'ghana': 'GH',
    'gibraltar': 'GI',
    'greece': 'GR',
    'greenland': 'GL',
    'grenada': 'GD',
    'guadeloupe': 'GP',
    'guam': 'GU',
    'guatemala': 'GT',
    'guinea': 'GN',
    'guyana': 'GY',
    'haiti': 'HT',
    'honduras': 'HN',
    'hong kong': 'HK',
    'hungary': 'HU',
    'iceland': 'IS',
    'india': 'IN',
    'indonesia': 'ID',
    'iraq': 'IQ',
    'ireland': 'IE',
    'israel': 'IL',
    'italy': 'IT',
    'jamaica': 'JM',
    'japan': 'JP',
    'jordan': 'JO',
    'kazakhstan': 'KZ',
    'kenya': 'KE',
    'kiribati': 'KI',
    'korea, republic of': 'KR',
    'kuwait': 'KW',
    'kyrgyzstan': 'KG',
    'lao people s democratic republic': 'LA',
    'latvia': 'LV',
    'lebanon': 'LB',
    'lesotho': 'LS',
    'liberia': 'LR',
    'libyan arab jamahiriya': 'LY',
    'liechtenstein': 'LI',
    'lithuania': 'LT',
    'luxembourg': 'LU',
    'macao': 'MO',
    'macedonia, the former yugoslav republic of': 'MK',
    'madagascar': 'MG',
    'malawi': 'MW',
    'malaysia': 'MY',
    'maldives': 'MV',
    'mali': 'ML',
    'malta': 'MT',
    'marshall islands': 'MH',
    'martinique': 'MQ',
    'mauritania': 'MR',
    'mauritius': 'MU',
    'mayotte': 'YT',
    'mexico': 'MX',
    'micronesia, federated states of': 'FM',
    'moldova, republic of': 'MD',
    'monaco': 'MC',
    'mongolia': 'MN',
    'montserrat': 'MS',
    'morocco': 'MA',
    'mozambique': 'MZ',
    'myanmar': 'MM',
    'namibia': 'NA',
    'nauru': 'NR',
    'nepal': 'NP',
    'netherlands': 'NL',
    'new caledonia': 'NC',
    'new zealand': 'NZ',
    'nicaragua': 'NI',
    'niger': 'NE',
    'nigeria': 'NG',
    'niue': 'NU',
    'norfolk island': 'NF',
    'northern mariana islands': 'MP',
    'norway': 'NO',
    'oman': 'OM',
    'pakistan': 'PK',
    'palau': 'PW',
    'palestinian territory, occupied': 'PS',
    'panama': 'PA',
    'papua new guinea': 'PG',
    'paraguay': 'PY',
    'peru': 'PE',
    'philippines': 'PH',
    'poland': 'PL',
    'portugal': 'PT',
    'puerto rico': 'PR',
    'qatar': 'QA',
    'romania': 'RO',
    'russian federation': 'RU',
    'rwanda': 'RW',
    'réunion': 'RE',
    'saint kitts and nevis': 'KN',
    'saint lucia': 'LC',
    'saint pierre and miquelon': 'PM',
    'saint vincent and the grenadines': 'VC',
    'samoa': 'WS',
    'san marino': 'SM',
    'sao tome and principe': 'ST',
    'saudi arabia': 'SA',
    'senegal': 'SN',
    'serbia and montenegro': 'CS',
    'seychelles': 'SC',
    'sierra leone': 'SL',
    'singapore': 'SG',
    'slovakia': 'SK',
    'slovenia': 'SI',
    'solomon islands': 'SB',
    'somalia': 'SO',
    'south africa': 'ZA',
    'spain': 'ES',
    'sri lanka': 'LK',
    'sudan (the)': 'SD',
    'suriname': 'SR',
    'svalbard and jan mayen': 'SJ',
    'sweden': 'SE',
    'switzerland': 'CH',
    'syrian arab republic': 'SY',
    'taiwan': 'TW',
    'tajikistan': 'TJ',
    'tanzania, united republic of': 'TZ',
    'thailand': 'TH',
    'timor-leste': 'TL',
    'togo': 'TG',
    'tokelau': 'TK',
    'tonga': 'TO',
    'trinidad and tobago': 'TT',
    'tunisia': 'TN',
    'turkey': 'TR',
    'turkmenistan': 'TM',
    'turks and caicos islands': 'TC',
    'tuvalu': 'TV',
    'uganda': 'UG',
    'ukraine': 'UA',
    'united arab emirates': 'AE',
    'united kingdom': 'GB',
    'united states': 'US',
    'united states minor outlying islands': 'UM',
    'uruguay': 'UY',
    'uzbekistan': 'UZ',
    'vanuatu': 'VU',
    'venezuela': 'VE',
    'viet nam': 'VN',
    'virgin islands, british': 'VG',
    'virgin islands, u.s.': 'VI',
    'wallis and futuna': 'WF',
    'western sahara': 'EH',
    'worldwide': 'WW',
    'yemen': 'YE',
    'zambia': 'ZM',
    'zimbabwe': 'ZW',
    'åland islands': 'AX',
}


def country_code(name):
    """Код страны по названию — или само название, если оно незнакомо."""
    if not name:
        return name
    return COUNTRY_CODES.get(" ".join(str(name).split()).casefold(), name)
